### ISSUE TITLE
Compilation error on master

### ISSUE THREAD

**Issue by rodrigues** [mneudert/geolix#14]
I get a compilation error on master:

```shell
==> geolix
Compiling 37 files (.ex)

== Compilation error on file lib/geolix/adapter/mmdb2/decoder.ex ==
** (CompileError) Elixir.Geolix.Adapter.MMDB2.Decoder: function value/2+15:
  Internal consistency check failed - please report this bug.
  Instruction: {call,2,{f,7}}
  Error:       {multiple_match_contexts,[{x,1},0]}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

could not compile dependency :geolix, "mix compile" failed. You can recompile this dependency with "mix deps.compile geolix", update it with "mix deps.update geolix" or clean it with "mix deps.clean geolix"
```

**Comment by mneudert** [comment]
Can you tell me which Erlang/Elixir combination you are using?

From what I can find out about this type of error message it might be something down at the Erlang level worth tracking down.

**Comment by rodrigues** [comment]
```shell
rodrigues@victor ~/Code/open/geolix (master)$ iex -v
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

IEx 1.3.2
```

**Comment by mneudert** [comment]
Oh, I just found another more viable workaround for the problem: removing the case statement around the issue!

Pushed a commit for that to the branch [erlang-19](https://github.com/mneudert/geolix/tree/erlang-19). If that one works for you I would merge it into master.

(Release `v0.10.1` should work without problems as the offending commit 0653b09 is not included there)

**Comment by rodrigues** [comment]
hi @mneudert, indeed, all beautiful and shining on `erlang-19` branch for me 😀

**Comment by mneudert** [comment]
I was actually able to narrow that issue down to a minimal module and have linked details in an open issue I found for that error. Hope someone finds more than just workarounds for that problem.

Thanks for making me aware of this :)
