### ISSUE TITLE
README.md Wrong

### ISSUE THREAD

**Issue by mattludwigs** [mneudert/geolix#15]
In the README.md to download I used:

```
defp deps do
  [ { :geolix, "~> 0.10" } ]
end
```

And followed the documentation in the README I could not start the Database.Loader correctly. After exploring my deps and the current source code it seems that the README should work for the `0.11.0` code, whereas it does not work for `~> 0.10`. Maybe updating the version should be the same version in the `mix.exs` file?

**Comment by mneudert** [comment]
You are probably looking for the README of the tag you are using ([GitHub](https://github.com/mneudert/geolix/tree/v0.10.1) and [HexDocs](https://hexdocs.pm/geolix/0.10.1/readme.html)).

The dependency statement is valid for real releases and not the `0.11.0-dev` only available via GitHub. Rest assured you are not the only one tripping over that :D

Could you think of some statement I could include to mention that difference? Might help to prevent the confusion...

**Comment by mattludwigs** [comment]
Yeah I was able to find the correct docs in the README found from the hex package under my deps directory, and from there everything worked great, so thanks for building a solid working package!

As far as including a statement, I am really bad at writing these types of things but maybe in include something along the lines of:

```
Documentation below is for the 0.11.0-dev release. Please see <insert some link or instructions here> for documentation for ~> 0.10 releases.
```

By the way, I am very excited about 0.11 after exploring the source code and docs for both versions!  Cannot wait for the release, and thank you for working on this package!

**Comment by mneudert** [comment]
I tried to word it in a way that someone reading it on Hex is not confused and I don't have to modify it for upcoming versions. Should be good enough for now. And as a new release is around the corner the current problem will vanish for some time anyway :D
