### ISSUE TITLE
Error: bad request with valid filename

### ISSUE THREAD

**Issue by acconrad** [mneudert/geolix#8]
`Geolix.set_database(:city, "https://s3-us-west-2.amazonaws.com/ip-profiler/GeoLite2-City.mmdb")`

Returns an error claiming the file doesn't exist, but you can go to it [here](https://s3-us-west-2.amazonaws.com/ip-profiler/GeoLite2-City.mmdb) and it is perfectly valid. I'm currently running:

* Erlang 18.1.3
* Elixir 1.1.1
* Phoenix 1.0.4
* Geolix 0.9

I set up the plugin exactly as specified in the documentation. If you need any more information or help let me know!

**Comment by mneudert** [comment]
Well, for the library the file does not "exist" in the sense that it is not available on the local filesystem. Currently the file gets read in `Geolix.Reader.read_database/1` by using `File.read!/1`. But that only works for local files.

To have your use case covered it would be necessary to switch over to a solution like `Mix.Utils.read_path/2` does. With the file being completely read into memory before parsing and afterwards not getting accessed anymore that should not be a big problem.

If you say that would be a good addition (or necessary in your AWS environment) I would go ahead and patch something up for that.

**Comment by acconrad** [comment]
@mneudert thanks for the reply! I actually tried that first by saving my `.mmdb` files to my Phoenix project repo (specifically in `/priv/static/profiler/GeoLite-2-C*.mmdb`) but when I tried to do `Geolix.set_database(:city, "/static/profiler/GeoLite-2-C*.mmdb")` it also couldn't find it. Do you have a working example of a Phoenix project with a `.mmdb` file? I tried checking out the test suite but you do some funky loading for your sample MMDB files which doesn't exactly align with the way you would put something in a `config.exs` file.

**Comment by mneudert** [comment]
The path should be an absolute path to the file. It will be taken as is for reading the file.

If you configure "/static/profiler/..." (with a leading slash) then it will look for a directory "static" in the root of your file system, not in your project nor in your projects priv dir. You should be fine if you configure something like this:

```elixir
city_path = 
     [ :code.priv_dir(:your_application), "static/profiler/GeoLite2-City.mmdb" ]
  |> Path.join()
  |> Path.expand()

config :geolix, databases: [{ :city, city_path }]
```
Using `:code.priv_dir(:your_application)` you should get the right path. A different approach would be to use `__DIR__`:

```elixir
city_path = 
     [ __DIR__, "../priv/static/profiler/GeoLite2-City.mmdb" ]
  |> Path.join()
  |> Path.expand()

config :geolix, databases: [{ :city, city_path }]
```

Both should create the correct path to your projects priv directory and the file in it.

Or you could use a relative path like I do for the [verification tests](https://github.com/mneudert/geolix/blob/master/verify/geolix/config/config.exs). But the way these relative paths are resolved (relative to the directory you invoked mix in) makes this something you probably don't want to use...

**Comment by acconrad** [comment]
@mneudert this is great, it worked! Thank you, I could add this to your README if you'd like, I can also create a PR using something like [httpoison](https://github.com/edgurgel/httpoison) or [tesla](https://github.com/monterail/tesla) to grab the file from a remote URL. Would you be interested in something like that as well? Happy holidays!

**Comment by mneudert** [comment]
A PR for the documentation would be great!

Regarding the http client I would like to go with a pure `:httpc` implementation. Everything else would only introduce a whole bunch of new dependencies that might not be worth the hassle. Otherwise I say you should give it a shot :)
